### ISSUE TITLE
Consideration: Make question an action interface defenition

### ISSUE THREAD

**Issue by Timple** [LoyVanBeek/instant_messaging_interfaces#1]
When the question is no longer relevant, you can preempt etc.

Just an idea, your repo popped up in my feed and we have an action interface providing this.

**Comment by LoyVanBeek** [comment]
The `Options` message could be composed into a `QuestionActionGoal` indeed. 

For now, this is package is meant as a place to put the decoupled interface that would otherwise be part of my [`telegram_ros2`](https://github.com/LoyVanBeek/telegram_ros2/) which you might like. 
Since chat apps/APIs (AFAIK) don't have a concept of an Action, my current plan is to make a simple, shallow bridge (it gets your feet wet?). 

At @tue-robotics, the `Question`-Action is built on a much higher level:
The `conversation_engine` implements a `hmi_server` and the `conversation_engine` communicates with the telegram bridge. The application state machines have a `hmi_client`

**Comment by Timple** [comment]
Well, having a bridge just doing conversions would indeed be clean.

**Comment by Timple** [comment]
Explanation given
